global:
  scrape_interval: 30s
  evaluation_interval: 30s
  # Optimize storage for free tier
  storage_retention: 7d
  storage_retention_size: 5GB

scrape_configs:
  - job_name: "mlflow"
    static_configs:
      - targets: ["localhost:5000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "qdrant"
    static_configs:
      - targets: ["localhost:6333"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]
    scrape_interval: 30s

storage:
  tsdb:
    # Optimize for free tier storage
    retention: 7d
    min_block_duration: 2h
    max_block_duration: 24h

# Memory optimization
memory:
  chunks: 1048576 # 1M chunks
  max_samples_per_chunk: 120
  max_chunks_to_persist: 524288
