global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "mlflow"
    static_configs:
      - targets: ["localhost:5000"]
    metrics_path: "/metrics"

  - job_name: "qdrant"
    static_configs:
      - targets: ["localhost:6333"]
    metrics_path: "/metrics"

  - job_name: "node"
    static_configs:
      - targets: ["localhost:9100"]

remote_write:
  - url: "https://prometheus-blocks-prod-us-central1.grafana.net/api/v1/write"
    basic_auth:
      username: "12345"  # Replace with your Grafana Cloud account ID
      password: "api_key_generated_from_grafana_cloud"  # Replace with your Grafana Cloud API Key