name: 'Infrastructure Monitoring'

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to monitor (dev or prod)"
        required: true
        default: "dev"

env:
  TF_VAR_tenancy_ocid: ${{ secrets.OCI_TENANCY_OCID }}
  TF_VAR_user_ocid: ${{ secrets.OCI_USER_OCID }}
  TF_VAR_fingerprint: ${{ secrets.OCI_FINGERPRINT }}
  TF_VAR_region: ${{ secrets.OCI_REGION }}

jobs:
  check-services:
    name: 'Service Health Check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup OCI CLI
        run: |
          mkdir -p ~/.oci
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "${{ secrets.DEV_OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "${{ secrets.PROD_OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          fi
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Check MLflow Health
        id: check-mlflow
        continue-on-error: true
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.MLFLOW_URL }}/health)
          if [ $status_code -ne 200 ]; then
            echo "MLflow is down (Status: $status_code)"
            exit 1
          fi
          echo "MLflow is healthy"

      - name: Check Qdrant Health
        id: check-qdrant
        continue-on-error: true
        run: |
          status_code=$(curl -s -o /dev/null -w "%{http_code}" ${{ secrets.QDRANT_URL }}/health)
          if [ $status_code -ne 200 ]; then
            echo "Qdrant is down (Status: $status_code)"
            exit 1
          fi
          echo "Qdrant is healthy"

      - name: Notify if Services Down
        if: ${{ failure() }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "Service Health Alert"
          message_format: "🚨 *Service Health Alert*\nEnvironment: ${{ github.event.inputs.environment }}\nMLflow: ${{ steps.check-mlflow.outcome }}\nQdrant: ${{ steps.check-qdrant.outcome }}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  resource-checks:
    name: 'Resource Usage Check'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup OCI CLI
        run: |
          mkdir -p ~/.oci
          if [[ "${{ github.event.inputs.environment }}" == "dev" ]]; then
            echo "${{ secrets.DEV_OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          elif [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "${{ secrets.PROD_OCI_PRIVATE_KEY }}" > ~/.oci/oci_api_key.pem
          fi
          chmod 600 ~/.oci/oci_api_key.pem

      - name: Check Resources
        run: python3 scripts/monitoring/check_resources.py \
            --max-ocpus 1 --max-memory-gb 6 --max-instances 4

      - name: Notify on Resource Issues
        if: ${{ failure() }}
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notification_title: "Resource Usage Alert"
          message_format: "⚠️ Resource Limits Warning\n{message}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  collect-metrics:
    name: 'Collect Metrics'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Collect MLflow Metrics
        run: python3 scripts/monitoring/collect_metrics.py \
              --service mlflow \
              --url ${{ secrets.MLFLOW_URL }} \
              --output mlflow_metrics.json

      - name: Collect Qdrant Metrics
        run: python3 scripts/monitoring/collect_metrics.py \
              --service qdrant \
              --url ${{ secrets.QDRANT_URL }} \
              --output qdrant_metrics.json

      - name: Upload Metrics
        uses: actions/upload-artifact@v3
        with:
          name: collected-metrics
          path: "*.json"